#
# Copyright IBM Corp All Rights Reserved
#
# SPDX-License-Identifier: Apache-2.0
#
version: '2'

networks:
  basic:

services:
  ca-base:
    image: hyperledger/fabric-ca
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
    networks:
      - basic

  # ORG1 CA
  ca.org1.example.com:
    extends:
      service: ca-base
    environment:
      - FABRIC_CA_SERVER_CA_NAME=ca.org1.example.com
      - FABRIC_CA_SERVER_CA_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.org1.example.com-cert.pem
      - FABRIC_CA_SERVER_CA_KEYFILE=/etc/hyperledger/fabric-ca-server-config/e4530b45f2112860bb3a9cdb51b71eaaf8498f6782371c201576d674d01dd8d2_sk
    ports:
      - "17054:7054"
    command: sh -c 'fabric-ca-server start -b admin:adminpw'
    volumes:
      - ./crypto-config/peerOrganizations/org1.example.com/ca/:/etc/hyperledger/fabric-ca-server-config
    container_name: ca.org1.example.com
    networks:
      - basic

  # ORG2 CA
  ca.org2.example.com:
    extends:
      service: ca-base
    environment:
      - FABRIC_CA_SERVER_CA_NAME=ca.org2.example.com
      - FABRIC_CA_SERVER_CA_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.org2.example.com-cert.pem
      - FABRIC_CA_SERVER_CA_KEYFILE=/etc/hyperledger/fabric-ca-server-config/4626c1c939f1253d75024e8e424d4852925de7cdd8e179505fc241f62afac577_sk
    ports:
      - "27054:7054"
    command: sh -c 'fabric-ca-server start -b admin:adminpw'
    volumes:
      - ./crypto-config/peerOrganizations/org2.example.com/ca/:/etc/hyperledger/fabric-ca-server-config
    container_name: ca.org2.example.com
    networks:
      - basic

  # ORG3 CA
  ca.org3.example.com:
    extends:
      service: ca-base
    environment:
      - FABRIC_CA_SERVER_CA_NAME=ca.org3.example.com
      - FABRIC_CA_SERVER_CA_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.org3.example.com-cert.pem
      - FABRIC_CA_SERVER_CA_KEYFILE=/etc/hyperledger/fabric-ca-server-config/0ff6b7319f98c7088ad5d150ca1026649d2cc65bfca15ffa80f83d19aab4cf47_sk
    ports:
      - "37054:7054"
    command: sh -c 'fabric-ca-server start -b admin:adminpw'
    volumes:
      - ./crypto-config/peerOrganizations/org3.example.com/ca/:/etc/hyperledger/fabric-ca-server-config
    container_name: ca.org3.example.com
    networks:
      - basic

  # ORG4 CA
  ca.org4.example.com:
    extends:
      service: ca-base
    environment:
      - FABRIC_CA_SERVER_CA_NAME=ca.org4.example.com
      - FABRIC_CA_SERVER_CA_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.org4.example.com-cert.pem
      - FABRIC_CA_SERVER_CA_KEYFILE=/etc/hyperledger/fabric-ca-server-config/9af7552a3e5bc4a622047d2dbe9d7a57372b64086edb1418f7eed6376789c7d7_sk
    ports:
      - "47054:7054"
    command: sh -c 'fabric-ca-server start -b admin:adminpw'
    volumes:
      - ./crypto-config/peerOrganizations/org4.example.com/ca/:/etc/hyperledger/fabric-ca-server-config
    container_name: ca.org4.example.com
    networks:
      - basic
            
  orderer.example.com:
    container_name: orderer.example.com
    image: hyperledger/fabric-orderer
    environment:
      - FABRIC_LOGGING_SPEC=info
      - ORDERER_GENERAL_LISTENADDRESS=0.0.0.0
      - ORDERER_GENERAL_GENESISMETHOD=file
      - ORDERER_GENERAL_GENESISFILE=/etc/hyperledger/configtx/genesis.block
      - ORDERER_GENERAL_LOCALMSPID=OrdererMSP
      - ORDERER_GENERAL_LOCALMSPDIR=/etc/hyperledger/msp/orderer/msp
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/orderer
    command: orderer
    ports:
      - 7050:7050
    volumes:
        - ./config/:/etc/hyperledger/configtx
        - ./crypto-config/ordererOrganizations/example.com/orderers/orderer.example.com/:/etc/hyperledger/msp/orderer
        - ./crypto-config/peerOrganizations/org1.example.com/peers/peer0.org1.example.com/:/etc/hyperledger/msp/peerOrg1
    networks:
      - basic

  peer-base:
    image: hyperledger/fabric-peer
    environment:
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - FABRIC_LOGGING_SPEC=info
      - CORE_CHAINCODE_LOGGING_LEVEL=info
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=${COMPOSE_PROJECT_NAME}_basic
      - CORE_PEER_GOSSIP_USELEADERELECTION=true
      - CORE_PEER_GOSSIP_ORGLEADER=false                
      - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      # The CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME and CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD
      # provide the credentials for ledger to connect to CouchDB.  The username and password must
      # match the username and password set for the associated CouchDB.
      - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=
      - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=      

    working_dir: /opt/gopath/src/github.com/hyperledger/fabric
    command: peer node start
    volumes:
      - /var/run/:/host/var/run/
      - ./config:/etc/hyperledger/configtx
    networks:
      - basic

  peer0.org1.example.com:
    extends:
      service: peer-base
    container_name: peer0.org1.example.com
    environment:
      - CORE_PEER_ID=peer0.org1.example.com
      - CORE_PEER_LOCALMSPID=Org1MSP
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/msp/users/Admin@org1.example.com/msp
      - CORE_PEER_ADDRESS=peer0.org1.example.com:17051   
      - CORE_PEER_LISTENADDRESS=0.0.0.0:17051        
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb1:5984
      - CORE_PEER_CHAINCODEADDRESS=peer0.org1.example.com:17053
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:17053      
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.org1.example.com:17051 peer1.org1.example.com:18051 peer2.org1.example.com:19051 
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.org1.example.com:17051        
    ports:
      - 17051:17051
      - 17053:17053
    volumes:
        - ./crypto-config/peerOrganizations/org1.example.com/peers/peer0.org1.example.com/msp:/etc/hyperledger/msp/peer
        - ./crypto-config/peerOrganizations/org1.example.com/users:/etc/hyperledger/msp/users
    depends_on:
      - orderer.example.com
      - couchdb1

  peer1.org1.example.com:
    extends:
      service: peer-base
    container_name: peer1.org1.example.com
    environment:
      - CORE_PEER_ID=peer1.org1.example.com
      - CORE_PEER_LOCALMSPID=Org1MSP
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/msp/users/Admin@org1.example.com/msp
      - CORE_PEER_ADDRESS=peer1.org1.example.com:18051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:18051        
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb1:5984
      - CORE_PEER_CHAINCODEADDRESS=peer1.org1.example.com:18053
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:18053      
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.org1.example.com:17051 peer1.org1.example.com:18051 peer2.org1.example.com:19051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1.org1.example.com:18051    
    ports:
      - 18051:18051
      - 18053:18053
    volumes:
        - ./crypto-config/peerOrganizations/org1.example.com/peers/peer1.org1.example.com/msp:/etc/hyperledger/msp/peer
        - ./crypto-config/peerOrganizations/org1.example.com/users:/etc/hyperledger/msp/users
    depends_on:
      - orderer.example.com
      - couchdb1

  peer2.org1.example.com:
    extends:
      service: peer-base
    container_name: peer2.org1.example.com
    environment:
      - CORE_PEER_ID=peer2.org1.example.com
      - CORE_PEER_LOCALMSPID=Org1MSP
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/msp/users/Admin@org1.example.com/msp
      - CORE_PEER_ADDRESS=peer2.org1.example.com:19051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:19051        
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb1:5984
      - CORE_PEER_CHAINCODEADDRESS=peer2.org1.example.com:19053
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:19053      
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.org1.example.com:17051 peer1.org1.example.com:18051 peer2.org1.example.com:19051 
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer2.org1.example.com:19051    
    ports:
      - 19051:19051
      - 19053:19053
    volumes:
        - ./crypto-config/peerOrganizations/org1.example.com/peers/peer2.org1.example.com/msp:/etc/hyperledger/msp/peer
        - ./crypto-config/peerOrganizations/org1.example.com/users:/etc/hyperledger/msp/users
    depends_on:
      - orderer.example.com
      - couchdb1

  peer0.org2.example.com:
    extends:
      service: peer-base
    container_name: peer0.org2.example.com
    environment:
      - CORE_PEER_ID=peer0.org2.example.com
      - CORE_PEER_LOCALMSPID=Org2MSP
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/msp/users/Admin@org2.example.com/msp
      - CORE_PEER_ADDRESS=peer0.org2.example.com:27051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:27051        
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb2:5984
      - CORE_PEER_CHAINCODEADDRESS=peer0.org2.example.com:27053
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:27053      
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.org2.example.com:27051 peer1.org2.example.com:28051  
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.org2.example.com:27051   
    ports:
      - 27051:27051
      - 27053:27053
    volumes:
        - ./crypto-config/peerOrganizations/org2.example.com/peers/peer0.org2.example.com/msp:/etc/hyperledger/msp/peer
        - ./crypto-config/peerOrganizations/org2.example.com/users:/etc/hyperledger/msp/users
    depends_on:
      - orderer.example.com
      - couchdb2

  peer1.org2.example.com:
    extends:
      service: peer-base
    container_name: peer1.org2.example.com
    environment:
      - CORE_PEER_ID=peer1.org2.example.com
      - CORE_PEER_LOCALMSPID=Org2MSP
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/msp/users/Admin@org2.example.com/msp
      - CORE_PEER_ADDRESS=peer1.org2.example.com:28051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:28051        
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb2:5984
      - CORE_PEER_CHAINCODEADDRESS=peer1.org2.example.com:28053
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:28053      
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.org2.example.com:27051 peer1.org2.example.com:28051 
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1.org2.example.com:28051   
    ports:
      - 28051:28051
      - 28053:28053
    volumes:
        - ./crypto-config/peerOrganizations/org2.example.com/peers/peer1.org2.example.com/msp:/etc/hyperledger/msp/peer
        - ./crypto-config/peerOrganizations/org2.example.com/users:/etc/hyperledger/msp/users
    depends_on:
      - orderer.example.com
      - couchdb2

  peer0.org3.example.com:
    extends:
      service: peer-base
    container_name: peer0.org3.example.com
    environment:
      - CORE_PEER_ID=peer0.org3.example.com
      - CORE_PEER_LOCALMSPID=Org3MSP
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/msp/users/Admin@org3.example.com/msp
      - CORE_PEER_ADDRESS=peer0.org3.example.com:37051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:37051        
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb3:5984
      - CORE_PEER_CHAINCODEADDRESS=peer0.org3.example.com:37053
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:37053      
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.org3.example.com:37051 peer1.org3.example.com:38051 
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.org3.example.com:37051   
    ports:
      - 37051:37051
      - 37053:37053
    volumes:
        - ./crypto-config/peerOrganizations/org3.example.com/peers/peer0.org3.example.com/msp:/etc/hyperledger/msp/peer
        - ./crypto-config/peerOrganizations/org3.example.com/users:/etc/hyperledger/msp/users
    depends_on:
      - orderer.example.com
      - couchdb3

  peer1.org3.example.com:
    extends:
      service: peer-base
    container_name: peer1.org3.example.com
    environment:
      - CORE_PEER_ID=peer1.org3.example.com
      - CORE_PEER_LOCALMSPID=Org3MSP
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/msp/users/Admin@org3.example.com/msp
      - CORE_PEER_ADDRESS=peer1.org3.example.com:38051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:38051        
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb3:5984
      - CORE_PEER_CHAINCODEADDRESS=peer1.org3.example.com:38053
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:38053      
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.org3.example.com:37051 peer1.org3.example.com:38051 
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1.org3.example.com:38051   
    ports:
      - 38051:38051
      - 38053:38053
    volumes:
        - ./crypto-config/peerOrganizations/org3.example.com/peers/peer1.org3.example.com/msp:/etc/hyperledger/msp/peer
        - ./crypto-config/peerOrganizations/org3.example.com/users:/etc/hyperledger/msp/users
    depends_on:
      - orderer.example.com
      - couchdb3

  peer0.org4.example.com:
    extends:
      service: peer-base
    container_name: peer0.org4.example.com
    environment:
      - CORE_PEER_ID=peer0.org4.example.com
      - CORE_PEER_LOCALMSPID=Org4MSP
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/msp/users/Admin@org4.example.com/msp
      - CORE_PEER_ADDRESS=peer0.org4.example.com:47051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:47051        
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb4:5984
      - CORE_PEER_CHAINCODEADDRESS=peer0.org4.example.com:47053
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:47053      
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.org4.example.com:47051 peer1.org4.example.com:48051 
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.org4.example.com:47051  
    ports:
      - 47051:47051
      - 47053:47053
    volumes:
        - ./crypto-config/peerOrganizations/org4.example.com/peers/peer0.org4.example.com/msp:/etc/hyperledger/msp/peer
        - ./crypto-config/peerOrganizations/org4.example.com/users:/etc/hyperledger/msp/users
    depends_on:
      - orderer.example.com
      - couchdb4

  peer1.org4.example.com:
    extends:
      service: peer-base
    container_name: peer1.org4.example.com
    environment:
      - CORE_PEER_ID=peer1.org4.example.com
      - CORE_PEER_LOCALMSPID=Org4MSP
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/msp/users/Admin@org4.example.com/msp
      - CORE_PEER_ADDRESS=peer1.org4.example.com:48051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:48051        
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb4:5984
      - CORE_PEER_CHAINCODEADDRESS=peer1.org4.example.com:48053
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:48053      
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.org4.example.com:47051 peer1.org4.example.com:48051 
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1.org4.example.com:48051  
    ports:
      - 48051:48051
      - 48053:48053
    volumes:
        - ./crypto-config/peerOrganizations/org4.example.com/peers/peer1.org4.example.com/msp:/etc/hyperledger/msp/peer
        - ./crypto-config/peerOrganizations/org4.example.com/users:/etc/hyperledger/msp/users
    depends_on:
      - orderer.example.com
      - couchdb4

  couchdb-base:
    image: hyperledger/fabric-couchdb
    # Populate the COUCHDB_USER and COUCHDB_PASSWORD to set an admin user and password
    # for CouchDB.  This will prevent CouchDB from operating in an "Admin Party" mode.
    environment:
      - COUCHDB_USER=
      - COUCHDB_PASSWORD=
    networks:
      - basic

  couchdb1:
    extends:
      service: couchdb-base  
    container_name: couchdb1
    ports:
      - 15984:5984

  couchdb2:
    extends:
      service: couchdb-base      
    container_name: couchdb2
    ports:
      - 25984:5984

  couchdb3:
    extends:
      service: couchdb-base      
    container_name: couchdb3
    ports:
      - 35984:5984

  couchdb4:
    extends:
      service: couchdb-base      
    container_name: couchdb4
    ports:
      - 45984:5984

  cli-base:
    image: hyperledger/fabric-tools
    tty: true
    environment:
      - GOPATH=/opt/gopath
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - FABRIC_LOGGING_SPEC=info
      - CORE_CHAINCODE_KEEPALIVE=10
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: /bin/bash
    volumes:
        - /var/run/:/host/var/run/
        - ./config/:/etc/hyperledger/configtx
        - ./crypto-config:/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/
        - ./../chaincode/:/opt/gopath/src/github.com/
    networks:
      - basic

  cli_org1:
    extends:
      service: cli-base  
    container_name: cli_org1
    environment:
      - CORE_PEER_ID=cli_org1
      - CORE_PEER_ADDRESS=peer0.org1.example.com:17051
      - CORE_PEER_LOCALMSPID=Org1MSP
      - CORE_PEER_MSPCONFIGPATH=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/org1.example.com/users/Admin@org1.example.com/msp
    depends_on:
     - orderer.example.com
     - peer0.org1.example.com
     - couchdb1

  cli_org2:
    extends:
      service: cli-base  
    container_name: cli_org2
    environment:
      - CORE_PEER_ID=cli_org2
      - CORE_PEER_ADDRESS=peer0.org2.example.com:27051
      - CORE_PEER_LOCALMSPID=Org2MSP
      - CORE_PEER_MSPCONFIGPATH=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/org2.example.com/users/Admin@org2.example.com/msp
    depends_on:
     - orderer.example.com
     - peer0.org2.example.com
     - couchdb2

  cli_org3:
    extends:
      service: cli-base  
    container_name: cli_org3
    environment:
      - CORE_PEER_ID=cli_org3
      - CORE_PEER_ADDRESS=peer0.org3.example.com:37051
      - CORE_PEER_LOCALMSPID=Org3MSP
      - CORE_PEER_MSPCONFIGPATH=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/org3.example.com/users/Admin@org3.example.com/msp
    depends_on:
     - orderer.example.com
     - peer0.org3.example.com
     - couchdb3

  cli_org4:
    extends:
      service: cli-base  
    container_name: cli_org4
    environment:
      - CORE_PEER_ID=cli_org4
      - CORE_PEER_ADDRESS=peer0.org4.example.com:47051
      - CORE_PEER_LOCALMSPID=Org4MSP
      - CORE_PEER_MSPCONFIGPATH=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/org4.example.com/users/Admin@org4.example.com/msp
    depends_on:
     - orderer.example.com
     - peer0.org4.example.com
     - couchdb4     
